version: "3.8"

services:
  flask_app:
    image: flask-app
    command: gunicorn --bind :4200 robot_app:app
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - nginx_network
      - database_network

  database:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=robot
      - POSTGRES_PASSWORD=robot
      - POSTGRES_DB=robot
    networks:
      - database_network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - nginx_network
    depends_on:
      - flask_app

networks:
  nginx_network:
    name: nginx_network
    driver: bridge
  database_network:
    name: database_network
    driver: bridge

volumes:
  postgres_data:
